import "@/styles/globals.scss";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import localFont from "next/font/local";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
  preload: true,
});

// Custom font using local font file.
// const geist = localFont({
//   src: "./_fonts/Geist-VariableFont_wght.ttf",
//   display: "swap",
//   variable: "--font-geist",
//   preload: true,
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: Readonly<{ children: React.ReactNode }>) => {
  return (
    <html lang="en" className={`${inter.variable}`}>
      <body>{children}</body>
    </html>
  );
};

export default RootLayout;
